[browser]
gatherUsageStats = false

[server]
headless = true
port = 8501

[theme]
base = "light"
backgroundColor = "#f2f5fb"
secondaryBackgroundColor = "#fcfeff"
textColor = "#0a121d"
primaryColor = "#00347b"
